from __future__ import annotations

from collections.abc import Mapping

from sqlalchemy import MetaData

from app.core.personas import PERSONA_KIND_COMMENT

COMMON_COLUMN_COMMENTS: dict[str, str] = {
    "id": "主键 ID；数据库使用数值自增 BIGINT，API 层按字符串返回。",
    "created_at": "记录创建时间（UTC）。",
    "updated_at": "记录最后更新时间（UTC）。",
    "deleted_at": "软删除时间；为空表示未删除。",
    "user_id": "关联用户 ID。",
    "board_id": "关联版块 ID。",
    "topic_id": "关联主题 ID。",
    "post_id": "关联帖子 ID。",
    "target_type": "目标对象类型。",
    "target_id": "目标对象 ID。",
    "type": "业务类型。",
    "status": "当前状态。",
    "slug": "URL 友好的唯一标识。",
    "name": "显示名称。",
}

TABLE_COMMENTS: dict[str, str] = {
    "users": "用户账号、权限角色、成长数值与账号状态。",
    "user_point_events": "用户可用积分和成长值流水，记录来源、变更值、幂等键与变更后快照。",
    "badge_definitions": "徽章定义目录，描述可展示徽章和信任等级门槛。",
    "user_badges": "用户徽章授予与撤销流水，保留来源、操作者和幂等键。",
    "user_trust_level_events": "用户信任等级变更流水，记录自动或人工调整前后快照。",
    "api_keys": "外部系统 API Key 元数据，仅保存令牌哈希、作用域、所有者和禁用状态。",
    "webhook_endpoints": "管理员配置的出站 Webhook 端点、订阅事件和签名密钥。",
    "webhook_deliveries": "Webhook 投递流水，记录事件载荷、尝试次数、响应和重试状态。",
    "external_integrations": "外部 provider 集成配置，保存启用状态、非公开配置和健康检查状态。",
    "external_integration_events": (
        "外部 provider 入站事件流水，记录验签、处理、重试和可展开资源摘要。"
    ),
    "ai_topic_summaries": "AI 主题摘要缓存，保存人工可刷新摘要、关键点、成本和生成元数据。",
    "push_subscriptions": "用户 Web Push 订阅端点，保存浏览器加密密钥、启用状态和撤销时间。",
    "boards": "论坛版块/分类及版块统计计数。",
    "board_members": "版块成员、角色与通知订阅级别。",
    "board_invitations": "邀请制版块的成员邀请生命周期记录。",
    "tags": "主题标签及标签使用计数。",
    "topics": "论坛主题主表，保存主题状态、计数与排序信号。",
    "topic_tags": "主题与标签的多对多关联表。",
    "posts": "主题内帖子/楼层内容，保存原始 Markdown 与安全 HTML。",
    "post_revisions": "帖子编辑历史版本，保存编辑前正文、编辑人、原因和恢复来源。",
    "topic_reads": "用户对主题的阅读进度与主题通知级别。",
    "topic_views": "主题浏览去重记录，用于保证同一浏览者只增加一次浏览数。",
    "site_visits": "站点访问事件，用于统计 PV、UV、来源渠道和入口页。",
    "reactions": "用户对主题或帖子的点赞等表态记录。",
    "bookmarks": "用户收藏的主题或帖子。",
    "notifications": "通知中心消息及阅读状态。",
    "flags": "内容举报、处理状态与处理结果。",
    "reviewables": "统一审核对象，承载举报、待审内容、自动规则和申诉处理状态。",
    "reviewable_events": "审核对象事件流水，记录认领、释放、处理和申诉。",
    "audit_logs": "审核与管理操作审计日志。",
    "email_verification_codes": "邮箱注册验证码记录，用于账号激活和重发限流。",
    "uploads": "用户上传的头像、帖子图片和附件元数据及存储引用。",
    "user_security_tokens": "账号找回、邮箱变更、跨项目登录等一次性安全令牌记录。",
    "product_access_grants": "跨产品用户资格授权，保存权限等级、期限、撤销与会话续验版本。",
    "user_sessions": "用户登录会话、刷新令牌哈希和设备撤销状态。",
    "user_recovery_codes": "TOTP 二次验证恢复码的哈希与使用状态。",
    "rate_limit_events": "写操作频控事件，用于用户/IP/邮箱等维度的滑动窗口计数。",
    "screened_rules": "邮箱、IP、URL 屏蔽名单规则及自动处置动作。",
    "spam_actions": "反垃圾系统自动拦截、禁言和频控处置记录。",
    "site_settings": "站点级可运营配置，包括品牌、注册开关和上传限制。",
    "background_jobs": "后台任务队列，保存待执行、重试、成功和死信任务。",
    "background_job_logs": "后台任务执行事件日志，用于排查失败、重试和死信。",
    "user_email_preferences": "用户邮件通知、摘要频率和投递禁用状态。",
    "email_delivery_events": "邮件供应商投递、退信和投诉事件记录。",
    "inbound_emails": "入站邮件回复 webhook 记录及匹配状态。",
    "backup_artifacts": "备份、导出归档元数据、校验和和状态记录。",
    "search_documents": "全文搜索索引文档，保存主题可搜索文本与过滤快照。",
    "search_logs": "搜索查询日志，用于无结果分析、热词统计和运营分析。",
    "drafts": "用户未发布的帖子与主题草稿，支持多设备恢复与冲突处理。",
    "daily_report_profiles": "用户个人日报助手配置，保存当前定制 Prompt 与版本。",
    "daily_report_prompt_versions": "个人日报 Prompt 的只增版本快照，支持追踪和回退。",
    "daily_report_sessions": "一次个人日报生成和多轮修改会话。",
    "daily_report_messages": "日报会话内按顺序保存的用户与助手消息。",
    "daily_reports": "用户确认后的最终日报历史，用于查看、复制与表达去重。",
    "user_relationships": "用户之间的关注、忽略和屏蔽关系。",
    "private_message_participants": "私信主题参与者及其已读状态。",
    "poll_votes": "用户对 Poll 选项的选择记录。",
    "poll_options": "Poll 的有序候选项。",
    "polls": "主题内简单 Poll 投票组件。",
    "votes": "用户对主题或帖子的赞成/反对投票记录。",
}

TABLE_COMMENTS.update(
    {
        "calendar_events": "社区日历活动，保存时间、地点、容量、提醒和关联主题。",
        "event_rsvps": "活动报名记录，保存用户 RSVP 状态和提醒发送状态。",
        "chat_channels": "实时聊天频道，保存频道类型、所属版块和消息统计。",
        "chat_channel_members": "聊天频道成员，保存角色和最后已读消息。",
        "chat_messages": "聊天消息记录，保存原始文本、删除状态和频道归属。",
        "chat_presence": "聊天在线与输入状态，保存用户在频道内的最近活跃时间。",
    }
)

COLUMN_COMMENTS: dict[str, dict[str, str]] = {
    "users": {
        "username": "登录名和公开显示用户名，唯一。",
        "email": "账号邮箱，唯一。",
        "hashed_password": "哈希后的登录密码。",
        "avatar_url": "用户头像 URL。",
        "role": "用户角色：普通用户、版主或管理员。",
        "level": "用户等级，默认 0，用于成长体系和权限展示。",
        "trust_level": "用户信任等级，独立于角色权限，用于反垃圾、上传和发链接风险控制。默认 0。",
        "trust_level_changed_at": "最近一次信任等级变化时间；为空表示尚未发生变化。",
        "points_balance": "用户当前可用积分余额，可由行为奖励、兑换或管理员调整。默认 0。",
        "experience_total": "用户累计成长值，用于按集中等级规则计算 level；兑换不扣减。默认 0。",
        "status": "账号状态：正常、禁言、封禁或删除。",
        "is_persona": "是否为运营维护的马甲账号；真实用户增长统计必须排除。",
        "persona_kind": PERSONA_KIND_COMMENT,
        "last_seen_at": "用户最后活跃时间。",
        "two_factor_enabled": "是否启用 TOTP 二次验证。",
        "two_factor_secret": "TOTP Base32 密钥；为空表示未完成启用。",
    },
    "user_point_events": {
        "user_id": "获得变更的用户 ID。",
        "source_type": "积分/成长值来源类型，如 topic_created、content_liked 或 admin_adjustment。",
        "source_id": "来源对象 ID；人工调整或系统事件可为空。",
        "points_delta": "本次积分变化量。",
        "experience_delta": "本次成长值变化量。",
        "balance_after": "变更后的积分余额。",
        "experience_after": "变更后的累计成长值。",
        "level_after": "变更后的用户等级快照。",
        "actor_id": "触发该变化的用户 ID；系统触发时为空。",
        "idempotency_key": "幂等键；同一业务事件只允许写入一次流水。",
        "note": "可审计备注。",
    },
    "badge_definitions": {
        "slug": "徽章稳定标识，用于自动授予和前端图标映射。",
        "name": "徽章显示名称。",
        "description": "徽章含义与获得条件说明。",
        "category": "徽章分类，如 account、participation、reputation 或 trust。",
        "icon": "徽章短图标或符号。",
        "trust_level_required": "展示或自动授予建议的最低信任等级。",
        "active": "徽章是否仍可授予。",
    },
    "user_badges": {
        "user_id": "获得徽章的用户 ID。",
        "badge_id": "关联徽章定义 ID。",
        "source_type": "授予来源类型，如 email_verified、topic_created 或 admin_manual。",
        "source_id": "来源对象 ID；系统或人工授予可为空。",
        "granted_by_id": "授予操作者 ID；自动授予时为空或为触发用户。",
        "revoked_at": "撤销时间；为空表示徽章当前有效。",
        "revoked_by_id": "撤销操作者 ID；用户删除后为空。",
        "revoke_reason": "撤销原因。",
        "idempotency_key": "幂等键；同一业务事件只允许写入一次徽章授予流水。",
        "note": "授予备注。",
    },
    "user_trust_level_events": {
        "user_id": "信任等级发生变化的用户 ID。",
        "previous_level": "变化前信任等级。",
        "next_level": "变化后信任等级。",
        "source_type": "触发信任重算或人工调整的来源类型。",
        "source_id": "来源对象 ID；系统或人工操作可为空。",
        "actor_id": "触发该变化的用户 ID；系统触发时为空。",
        "note": "变更原因或说明。",
    },
    "api_keys": {
        "name": "API Key 显示名称。",
        "token_prefix": "令牌前缀，用于管理员识别；不用于认证。",
        "token_hash": "高熵 API Key 的 SHA-256 哈希；不保存明文令牌。",
        "scopes": "允许访问的作用域数组；为空表示不能访问受保护接口。",
        "key_type": "Key 类型：admin 或 personal。",
        "owner_user_id": "个人令牌所属用户；系统级管理员令牌可为空。",
        "created_by_id": "创建该 Key 的管理员或用户 ID；删除后为空。",
        "last_used_at": "最近一次认证成功时间；为空表示从未使用。",
        "expires_at": "过期时间；为空表示不自动过期。",
        "disabled_at": "禁用时间；为空表示仍可使用。",
        "disabled_by_id": "禁用操作者 ID；为空表示未禁用或用户已删除。",
        "note": "管理员备注。",
    },
    "webhook_endpoints": {
        "name": "Webhook 端点显示名称。",
        "url": "接收 Webhook 的 HTTPS/HTTP URL。",
        "secret": "出站签名密钥；仅创建时返回给管理员，后续接口不明文展示。",
        "events": "订阅事件数组，如 topic.created、post.created 或 moderation.flag_created。",
        "active": "端点是否启用。",
        "created_by_id": "创建该端点的管理员 ID；删除后为空。",
        "disabled_at": "禁用时间；为空表示仍启用。",
        "disabled_by_id": "禁用操作者 ID；为空表示未禁用或用户已删除。",
        "note": "管理员备注。",
    },
    "webhook_deliveries": {
        "endpoint_id": "目标 Webhook 端点 ID。",
        "event_type": "投递事件类型。",
        "payload": "发送给接收方的 JSON 载荷快照。",
        "status": "投递状态：pending、retrying、succeeded、failed 或 disabled。",
        "attempt_count": "已尝试投递次数。",
        "max_attempts": "最大投递尝试次数。",
        "next_attempt_at": "下一次重试时间；无需重试时为空。",
        "last_status_code": "接收方最近一次 HTTP 状态码；网络错误时为空。",
        "last_error": "最近一次失败摘要。",
        "delivered_at": "成功投递时间；未成功时为空。",
        "response_body_excerpt": "接收方响应正文安全截断摘录。",
    },
    "external_integrations": {
        "provider": "外部集成 provider 标识，如 github、zendesk 或 patreon。",
        "enabled": "该 provider 是否启用。",
        "config": "provider 配置 JSON；响应层会隐藏 webhook_secret、api_token 等敏感键。",
        "created_by_id": "创建配置的管理员 ID；用户删除后为空。",
        "updated_by_id": "最后更新配置的管理员 ID；用户删除后为空。",
        "last_checked_at": "最近一次健康检查或配置保存时间；为空表示未检查。",
        "last_error": "最近一次集成处理错误摘要；为空表示无已知错误。",
    },
    "external_integration_events": {
        "provider": "事件来源 provider 标识。",
        "event_id": "provider 投递事件 ID，用于幂等处理。",
        "event_type": "provider 事件类型，如 GitHub issues。",
        "action": "provider 事件动作，如 opened、edited；为空表示未提供。",
        "payload": "入站事件安全截断载荷，不包含密钥。",
        "status": "处理状态：pending、processed、ignored、retrying 或 failed。",
        "signature_valid": "入站 webhook 是否通过 HMAC 验签。",
        "retry_count": "集成事件已重试次数。",
        "max_retries": "最大处理重试次数。",
        "next_retry_at": "下一次重试时间；无需重试时为空。",
        "processed_at": "事件成功处理或忽略时间；未完成时为空。",
        "last_error": "最近一次处理失败摘要。",
        "linked_resource_type": "关联外部资源类型，如 github_issue。",
        "linked_resource_id": "关联外部资源 ID 或编号。",
        "external_url": "外部资源 URL。",
        "title": "外部资源展示标题。",
    },
    "ai_topic_summaries": {
        "topic_id": "被总结的主题 ID，每个主题最多一条当前摘要。",
        "summary": "AI 生成或本地确定性生成的主题摘要。",
        "key_points": "关键结论或行动项数组。",
        "key_post_ids": "贡献摘要的关键帖子 ID 数组。",
        "model_name": "生成摘要的模型或本地算法名称。",
        "cost_units": "本次摘要估算成本单位，用于成本控制展示。",
        "refreshed_by_id": "触发刷新摘要的用户 ID；用户删除后为空。",
        "generated_at": "摘要生成时间。",
    },
    "push_subscriptions": {
        "user_id": "订阅所属用户 ID。",
        "endpoint": "浏览器 PushSubscription endpoint，用于去重；响应会安全截断展示。",
        "p256dh": "Web Push p256dh 公钥。",
        "auth_secret": "Web Push auth 密钥。",
        "user_agent": "订阅设备浏览器 User-Agent 摘要。",
        "enabled": "该推送订阅是否仍启用。",
        "last_sent_at": "最近一次尝试推送通知时间；为空表示尚未发送。",
        "disabled_at": "用户撤销或浏览器失效时间；为空表示仍启用。",
    },
    "email_verification_codes": {
        "user_id": "待验证用户 ID。",
        "email": "接收验证码的邮箱地址。",
        "code_hash": "验证码的不可逆哈希值。",
        "sent_at": "验证码邮件发送时间。",
        "expires_at": "验证码失效时间。",
        "consumed_at": "验证码成功使用时间；为空表示未使用。",
        "attempt_count": "该验证码已被尝试校验的次数。",
    },
    "boards": {
        "slug": "版块 URL 标识，唯一。",
        "name": "版块名称。",
        "name_localizations": "版块名称本地化映射，键为 BCP47 locale；为空表示使用 name。",
        "description": "版块说明与讨论范围。",
        "color": "版块主题色。",
        "avatar_url": "版块头像 URL。",
        "owner_id": "版块拥有者用户 ID；为空表示系统拥有。",
        "parent_board_id": "父版块 ID；为空表示顶层版块。",
        "visibility": "版块可见性：公开、私密或不列出。",
        "required_tags": "发帖必须包含的规范化标签名列表；为空或空数组表示不强制。",
        "allowed_tags": "允许使用的规范化标签名列表；为空或空数组表示不限制。",
        "post_template": "该版块新主题默认 Markdown 模板；为空表示不预填。",
        "default_notification_level": (
            "受邀成员或历史关注关系的默认版块通知级别；版块新帖订阅已退役。"
        ),
        "default_sort": "版块主题默认排序：latest、hot 或 top。",
        "topic_count": "版块下未删除主题数量缓存。",
        "post_count": "版块下帖子数量缓存。",
        "follower_count": "版块成员数量缓存；包含历史关注关系。",
    },
    "board_members": {
        "board_id": "所属版块 ID。",
        "user_id": "成员用户 ID。",
        "role": "成员在版块内的角色。",
        "notification_level": "该成员对版块的历史通知级别；不再触发版块新帖提醒。",
        "joined_at": "加入版块或建立历史关注关系的时间。",
    },
    "board_invitations": {
        "board_id": "被邀请加入的版块 ID。",
        "inviter_id": "发出邀请的用户 ID。",
        "invitee_id": "被邀请的用户 ID。",
        "status": "邀请状态：pending、accepted、declined、revoked 或 expired。",
        "expires_at": "邀请过期时间；为空表示当前首版不自动过期。",
        "responded_at": "邀请被接受、拒绝或撤回的时间。",
        "revoked_by_id": "撤回邀请的用户 ID；为空表示未撤回。",
    },
    "tags": {
        "name": "标签名称，唯一。",
        "slug": "标签 URL 标识，唯一。",
        "topic_count": "使用该标签的主题数量缓存。",
    },
    "topics": {
        "board_id": "主题所属版块 ID。",
        "user_id": "主题作者用户 ID。",
        "title": "主题标题。",
        "title_localizations": "主题标题本地化映射，键为 BCP47 locale；为空表示使用 title。",
        "slug": "主题 URL 标识，在同一版块内唯一。",
        "topic_type": "主题类型：regular 表示公开/版块主题，private_message 表示私信主题。",
        "visibility": (
            "主题可见性：public 表示沿用版块可见性，private_message 表示仅私信参与者可见。"
        ),
        "status": "主题状态：开放、关闭、归档或隐藏。",
        "pinned": "是否置顶主题。",
        "featured": "是否标记为精选主题。",
        "view_count": "主题浏览次数缓存。",
        "reply_count": "主题回复数量缓存。",
        "like_count": "主题点赞数量缓存。",
        "hot_score": "主题热度分，用于热门排序。",
        "last_posted_at": "最后发帖或回复时间。",
        "deleted_at": "主题软删除时间；为空表示未删除。",
        "merged_into_topic_id": "主题合并后的目标主题 ID；为空表示未合并。",
        "vote_count": "主题有效投票数量缓存。",
        "vote_score": "主题赞成票减反对票的缓存分数。",
        "answer_mode": "是否启用问答排序提示；有采纳答案时通常为 true。",
        "solved_by_id": "执行采纳或最后标记解决的用户 ID；为空表示未解决或用户已删除。",
        "solved_at": "主题被标记为已解决的时间；为空表示未解决。",
        "accepted_answer_post_id": "被采纳为解决方案的回复帖子 ID；为空表示未解决。",
    },
    "topic_tags": {
        "topic_id": "主题 ID。",
        "tag_id": "标签 ID。",
    },
    "posts": {
        "topic_id": "帖子所属主题 ID。",
        "user_id": "发帖用户 ID。",
        "parent_id": "父帖子 ID，用于楼中楼/引用回复。",
        "post_number": "主题内楼层编号。",
        "raw_md": "用户提交的原始 Markdown 内容。",
        "cooked_html": "服务端渲染/清洗后的 HTML 内容。",
        "reply_count": "该帖子的直接回复数量缓存。",
        "like_count": "该帖子的点赞数量缓存。",
        "vote_count": "帖子有效投票数量缓存。",
        "vote_score": "帖子赞成票减反对票的缓存分数。",
        "deleted_at": "帖子软删除时间；为空表示未删除。",
    },
    "post_revisions": {
        "post_id": "被编辑帖子 ID。",
        "topic_id": "被编辑帖子所属主题 ID，用于历史查询和审计关联。",
        "editor_id": "执行该次编辑或恢复操作的用户 ID；用户删除后为空。",
        "version_number": "同一帖子内递增的历史版本号，保存被覆盖前的内容版本。",
        "raw_md": "编辑前的原始 Markdown 内容。",
        "cooked_html": "编辑前已渲染/清洗的 HTML 内容。",
        "edit_reason": "编辑人填写的原因；为空表示未填写。",
        "summary": "系统生成或编辑人提供的版本摘要。",
        "restored_from_revision_id": "若该版本由恢复操作产生，指向被恢复的历史版本 ID；否则为空。",
        "created_at": "该历史版本保存时间（UTC）。",
    },
    "topic_reads": {
        "topic_id": "主题 ID。",
        "user_id": "用户 ID。",
        "last_read_post_number": "用户已读到的最高楼层编号。",
        "notification_level": "用户对该主题的通知级别。",
    },
    "topic_views": {
        "topic_id": "被浏览主题 ID。",
        "viewer_key": "浏览者去重键；保存登录用户或匿名访客标识的哈希，不保存原始访客 ID。",
        "first_viewed_at": "该浏览者首次计入主题浏览数的时间（UTC）。",
    },
    "site_visits": {
        "visitor_key": "访问者去重键；保存登录用户或匿名访客标识的哈希，不保存原始访客 ID。",
        "user_id": "登录访问者用户 ID；匿名访问为空。",
        "path": "访问的站内路径，包含查询字符串但不包含域名。",
        "title": "访问时浏览器页面标题；为空表示前端未提供。",
        "referrer_host": "来源 URL 的主机名；直接访问或无法解析时为空。",
        "source_type": "访问来源类型：direct、internal、search、social、referral 或 campaign。",
        "source_name": "归一化来源名称，如 Direct、Internal、baidu.com 或 utm_source。",
        "utm_source": "URL 查询参数 utm_source；为空表示未带广告/活动来源。",
        "utm_medium": "URL 查询参数 utm_medium；为空表示未带媒介。",
        "utm_campaign": "URL 查询参数 utm_campaign；为空表示未带活动名称。",
    },
    "reactions": {
        "target_type": "表态目标类型：主题或帖子。",
        "target_id": "表态目标 ID。",
        "user_id": "发起表态的用户 ID。",
        "type": "表态类型，目前为点赞。",
    },
    "bookmarks": {
        "target_type": "收藏目标类型：主题或帖子。",
        "target_id": "收藏目标 ID。",
        "user_id": "收藏用户 ID。",
    },
    "votes": {
        "target_type": "投票目标类型：topic 或 post。",
        "target_id": "投票目标 ID。",
        "user_id": "投票用户 ID。",
        "value": "投票值：1 表示赞成，-1 表示反对。",
    },
    "polls": {
        "topic_id": "关联主题 ID；首版每个主题最多一个 Poll。",
        "question": "Poll 问题文本。",
        "multiple_choice": "是否允许多选。",
        "closes_at": "Poll 截止时间；为空表示不自动截止。",
        "total_votes": "参与投票的去重用户数量缓存。",
    },
    "poll_options": {
        "poll_id": "所属 Poll ID。",
        "label": "选项展示文本。",
        "position": "选项排序，从 1 开始。",
        "vote_count": "选择该选项的投票数量缓存。",
    },
    "poll_votes": {
        "poll_id": "所属 Poll ID。",
        "option_id": "被选择的 Poll 选项 ID。",
        "user_id": "投票用户 ID。",
    },
    "notifications": {
        "user_id": "接收通知的用户 ID。",
        "type": "通知类型。",
        "topic_id": "关联主题 ID。",
        "post_id": "关联帖子 ID。",
        "actor_id": "触发通知的用户 ID。",
        "data": "通知展示所需的结构化扩展数据。",
        "read_at": "通知被读取的时间；为空表示未读。",
    },
    "flags": {
        "target_type": "被举报目标类型：主题或帖子。",
        "target_id": "被举报目标 ID。",
        "board_id": "举报内容所属版块 ID。",
        "reporter_id": "举报人用户 ID。",
        "reason": "举报原因。",
        "detail": "举报补充说明。",
        "status": "举报处理状态。",
        "resolution_note": "处理结论说明。",
        "resolved_by_id": "处理该举报的管理员/版主用户 ID。",
        "resolved_at": "举报处理完成时间。",
    },
    "reviewables": {
        "type": "审核对象类型：flag、queued_topic、queued_post、queued_edit、appeal 或 system。",
        "status": (
            "审核状态：pending、claimed、approved、rejected、hidden、deleted、"
            "silenced、escalated 或 appealed。"
        ),
        "priority": "审核优先级，数值越小越靠前。",
        "source": "审核来源，如 flag、content_safety 或 spam_rule。",
        "source_summary": "可展示的来源摘要，不包含敏感规则明文。",
        "target_type": "审核目标类型；待发布内容可为空。",
        "target_id": "审核目标 ID；待发布内容可为空。",
        "board_id": "相关版块 ID；全局审核对象为空。",
        "topic_id": "相关主题 ID；新主题待审时为空。",
        "post_id": "相关帖子 ID；新内容待审时为空。",
        "flag_id": "关联举报 ID；非举报来源为空。",
        "created_by_id": "创建审核项的用户 ID；系统创建时为空。",
        "target_user_id": "被审核或受处理影响的用户 ID。",
        "assigned_to_id": "当前认领审核员 ID；未认领为空。",
        "assigned_at": "审核项被认领时间；未认领为空。",
        "resolved_by_id": "最终处理审核员 ID；未处理为空。",
        "resolved_at": "最终处理时间；未处理为空。",
        "data": "审核上下文 JSON，普通用户接口不得返回敏感字段。",
    },
    "reviewable_events": {
        "reviewable_id": "关联审核对象 ID。",
        "actor_id": "触发事件的用户 ID；系统事件为空。",
        "event": "事件类型：created、claimed、released、decided 或 appealed。",
        "from_status": "事件前审核状态；创建事件为空。",
        "to_status": "事件后审核状态。",
        "note": "审核员备注或申诉理由。",
        "data": "事件上下文 JSON，不包含密码或令牌。",
        "created_at": "事件发生时间（UTC）。",
    },
    "audit_logs": {
        "actor_id": "执行操作的管理员/版主用户 ID。",
        "action": "审计动作类型。",
        "target_type": "被操作目标类型。",
        "target_id": "被操作目标 ID。",
        "board_id": "相关版块 ID。",
        "data": "动作上下文和变更前后的结构化数据。",
        "created_at": "审计日志记录时间（UTC）。",
    },
    "uploads": {
        "user_id": "上传文件的用户 ID。",
        "board_id": "附件归属版块 ID；临时文件或头像为空。",
        "topic_id": "附件归属主题 ID；临时文件或头像为空。",
        "post_id": "附件归属帖子 ID；临时文件或头像为空。",
        "original_filename": "用户上传时的原始文件名，仅用于展示和下载名。",
        "storage_backend": "文件存储后端：local 或 s3。",
        "storage_key": "存储后端内的对象键，唯一且不含本地绝对路径。",
        "media_type": "服务端嗅探确认后的 MIME 类型。",
        "byte_size": "上传文件字节数。",
        "sha256": "文件内容 SHA-256 摘要，用于去重和审计。",
        "kind": "上传用途：post_attachment 或 avatar。",
        "status": "上传状态：temporary、attached、avatar 或 deleted。",
        "is_image": "是否为可内联展示的图片。",
        "expires_at": "临时上传过期时间；为空表示不自动过期。",
        "deleted_at": "上传软删除时间；为空表示仍可按权限读取。",
    },
    "user_security_tokens": {
        "user_id": "安全令牌所属用户 ID。",
        "purpose": "令牌用途：password_reset 或 email_change。",
        "token_hash": "一次性令牌的不可逆哈希值。",
        "email": "令牌发送目标邮箱；为空表示使用用户当前邮箱。",
        "payload": "令牌附带的 JSON 数据，如新邮箱地址。",
        "sent_at": "令牌发送时间。",
        "expires_at": "令牌失效时间。",
        "consumed_at": "令牌成功使用时间；为空表示未使用。",
        "attempt_count": "该令牌已被尝试校验的次数。",
    },
    "product_access_grants": {
        "product": "外部产品稳定标识；首个接入值为 fablespace。",
        "user_id": "获得授权的论坛用户 ID。",
        "access_level": "产品权限等级：access、creator、operator 或 admin。",
        "granted_by_id": "最近一次授予或重新授予该资格的管理员 ID。",
        "expires_at": "授权到期时间（UTC）；为空表示不自动到期。",
        "revoked_at": "授权撤销时间（UTC）；为空表示未撤销。",
        "revoked_by_id": "最近一次撤销授权的管理员 ID。",
        "authorization_version": "授权状态版本；每次有效变更递增，供外部会话续验。",
    },
    "user_sessions": {
        "user_id": "会话所属用户 ID。",
        "refresh_token_hash": "刷新令牌的不可逆哈希值，用于撤销校验。",
        "user_agent": "登录设备/浏览器 User-Agent 摘要。",
        "ip_address": "登录请求来源 IP。",
        "last_seen_at": "该会话最后活跃时间。",
        "revoked_at": "会话撤销时间；为空表示仍有效。",
    },
    "user_recovery_codes": {
        "user_id": "恢复码所属用户 ID。",
        "code_hash": "恢复码的不可逆哈希值。",
        "used_at": "恢复码使用时间；为空表示仍可使用。",
    },
    "rate_limit_events": {
        "scope": "频控场景，如 register:ip 或 topic:user。",
        "identity_type": "频控主体类型：user、ip、email 或 account。",
        "identity_key": "频控主体归一化键。",
        "user_id": "触发频控事件的用户 ID；匿名路径为空。",
        "ip_address": "触发频控事件的请求来源 IP。",
        "created_at": "频控事件发生时间。",
    },
    "screened_rules": {
        "kind": "规则类型：email、ip 或 url。",
        "value": "管理员输入的原始屏蔽值。",
        "normalized_value": "用于匹配的归一化值。",
        "action": "命中后的处置动作：block 或 silence。",
        "note": "管理员备注；为空表示无备注。",
        "active": "规则是否启用。",
        "created_by_id": "创建规则的管理员 ID。",
    },
    "spam_actions": {
        "kind": "自动处置类型：rate_limit、screened_rule 或 new_user_screening。",
        "action": "自动处置动作：block 或 silence。",
        "reason": "触发处置的原因摘要。",
        "user_id": "被处置用户 ID；匿名注册/登录路径为空。",
        "ip_address": "触发处置的来源 IP。",
        "email": "命中的邮箱；非邮箱规则为空。",
        "url": "命中的 URL；非 URL 规则为空。",
        "screened_rule_id": "命中的屏蔽规则 ID；频控或新用户筛查为空。",
        "data": "处置上下文结构化数据，不包含密码或令牌。",
    },
    "site_settings": {
        "key": "设置键名，作为 API 与前端读取的稳定标识。",
        "value": "设置值，按 data_type 保存为 JSON 标量或对象。",
        "data_type": "设置值类型：string、boolean、integer 或 json。",
        "category": "设置分类，如 brand、access 或 uploads。",
        "description": "后台展示的设置说明。",
        "public": "是否可通过公开站点设置接口暴露给前端。",
        "updated_by_id": "最后修改该设置的管理员 ID；系统默认值为空。",
    },
    "background_jobs": {
        "queue": "任务队列名称，用于 worker 按队列拉取。",
        "task_name": "任务处理器名称。",
        "payload": "任务 JSON 载荷；不包含密码或大正文，邮件任务可含一次性发送密钥。",
        "status": "任务状态：queued、running、succeeded 或 dead。",
        "idempotency_key": "幂等键；非空时相同键只允许一个任务。",
        "priority": "任务优先级，数值越小越先执行。",
        "run_at": "任务最早可执行时间。",
        "attempts": "已尝试执行次数。",
        "max_attempts": "最大尝试次数，超过后进入 dead。",
        "locked_at": "任务被 worker 领取时间；为空表示未锁定。",
        "locked_by": "领取任务的 worker 标识。",
        "last_error": "最近一次失败错误摘要；成功时可为空。",
        "result": "任务成功结果摘要或失败上下文。",
        "finished_at": "任务最终完成或进入死信时间；未终结为空。",
    },
    "background_job_logs": {
        "job_id": "关联后台任务 ID。",
        "event": "任务事件类型，如 enqueued、started、succeeded、retry 或 dead。",
        "message": "事件说明。",
        "data": "事件结构化上下文，不包含密码、令牌或邮件密钥。",
        "created_at": "事件发生时间（UTC）。",
    },
    "user_email_preferences": {
        "user_id": "偏好所属用户 ID，唯一。",
        "email_enabled": "是否允许向该用户发送社区邮件。",
        "notify_replied": "被回复时是否发送邮件。",
        "notify_mentioned": "被提及时是否发送邮件。",
        "notify_liked": "帖子被点赞时是否发送邮件。",
        "notify_topic_new_post": "关注主题有新回复时是否发送邮件。",
        "notify_board_new_topic": "历史版块新主题邮件偏好；保留字段但不再发送。",
        "digest_frequency": "摘要邮件频率：off、daily 或 weekly。",
        "last_digest_sent_at": "上次摘要邮件发送时间；为空表示从未发送。",
        "delivery_status": "邮件投递状态：ok、bounced、complained 或 disabled。",
        "disabled_reason": "邮件被自动或手动停发的原因；为空表示未停发。",
        "quiet_hours_start": "免打扰开始小时（UTC，0-23）；为空表示未启用免打扰。",
        "quiet_hours_end": (
            "免打扰结束小时（UTC，0-23）；为空表示未启用免打扰；等于开始小时表示全天免打扰。"
        ),
    },
    "email_delivery_events": {
        "user_id": "匹配到的用户 ID；未知邮箱为空。",
        "email": "投递事件涉及的邮箱地址。",
        "event_type": "事件类型：sent、delivered、bounce、complaint 或 dropped。",
        "kind": "邮件业务类型，如 notification_replied 或 email_digest。",
        "provider_message_id": "邮件供应商消息 ID；为空表示供应商未提供。",
        "reason": "退信、投诉或丢弃原因摘要。",
        "payload": "供应商原始事件的安全摘录，不包含认证密钥。",
        "created_at": "事件记录时间（UTC）。",
    },
    "inbound_emails": {
        "from_email": "入站邮件发件人邮箱。",
        "user_id": "匹配到的站内用户 ID；未知发件人为空。",
        "topic_id": "邮件声称回复的主题 ID；无法匹配时为空或记录原值。",
        "post_id": "邮件声称回复的父帖子 ID；可为空。",
        "provider_message_id": "入站邮件供应商消息 ID。",
        "raw_md": "入站邮件转换后的 Markdown/纯文本正文。",
        "status": "处理状态：accepted、unknown_sender、topic_not_found 或 recorded。",
        "reason": "未接受或仅记录的原因摘要。",
        "payload": "入站 webhook 原始上下文的安全摘录。",
        "created_at": "入站邮件记录时间（UTC）。",
    },
    "backup_artifacts": {
        "kind": "归档类型：site_backup、site_export 或 user_export。",
        "status": "归档状态：queued、running、succeeded、failed 或 deleted。",
        "filename": "下载文件名。",
        "storage_backend": "归档存储后端，当前为 local。",
        "storage_key": "归档在存储后端内的对象键；未生成或删除时为空。",
        "byte_size": "归档文件字节数。",
        "sha256": "归档文件 SHA-256 校验和。",
        "metadata": "归档元数据、表计数和安全摘录；不包含密码或令牌明文。",
        "failure_reason": "备份失败原因摘要；成功时为空。",
        "created_by_id": "触发备份或导出的管理员 ID；用户删除后为空。",
        "completed_at": "归档成功、失败或删除完成时间；队列中为空。",
    },
    "search_documents": {
        "topic_id": "关联主题 ID。",
        "board_id": "关联版块 ID。",
        "author_id": "主题作者用户 ID。",
        "author_username": "主题作者用户名快照。",
        "topic_status": "主题状态快照：open、closed 或 archived。",
        "title": "搜索索引中的主题标题。",
        "body": "可见帖子 Markdown 聚合正文。",
        "tags_text": "标签名称、标签 slug 和作者名聚合文本。",
        "indexed_at": "索引文档最后生成时间（UTC）。",
    },
    "search_logs": {
        "user_id": "搜索用户 ID；匿名搜索为空。",
        "query": "用户原始搜索词截断快照。",
        "normalized_query": "归一化搜索词，用于热词和无结果分析。",
        "filters": "搜索过滤条件 JSON 快照。",
        "result_count": "本次搜索返回结果数量。",
        "has_results": "本次搜索是否有结果。",
    },
    "drafts": {
        "user_id": "草稿所属用户 ID。",
        "target_type": "草稿目标类型：new_topic 表示新主题，topic 表示某主题回复。",
        "target_id": "草稿目标 ID；新主题草稿为空字符串，回复草稿为主题 ID。",
        "draft_type": "草稿类型：topic (主题) 或 reply (回复)。",
        "data": "草稿结构化数据，保存标题、正文、标签等客户端状态。",
        "version": "草稿版本号，用于客户端-服务端冲突检测。",
    },
    "daily_report_profiles": {
        "custom_prompt": "用户可编辑的个人日报偏好 Prompt，不包含站点固定约束。",
        "preferences": "结构化日报偏好 JSON。",
        "prompt_version": "当前个人 Prompt 版本号。",
    },
    "daily_report_prompt_versions": {
        "profile_id": "关联日报配置 ID。",
        "version": "Prompt 快照版本号。",
        "custom_prompt": "该版本的个人偏好 Prompt。",
        "preferences": "该版本的结构化偏好 JSON。",
        "change_summary": "本次 Prompt 变更摘要。",
    },
    "daily_report_sessions": {
        "work_date": "日报对应的工作日期。",
        "status": "会话状态：active 或 confirmed。",
        "input_data": "用户本次提供的真实工作事实和输出风格。",
        "current_draft": "当前可编辑日报草稿。",
        "prompt_version": "创建会话时采用的个人 Prompt 版本。",
        "version": "会话乐观并发版本号。",
        "model_name": "最近一次生成草稿使用的模型名称。",
        "provider_mode": "最近一次生成模式：ai 或 local_fallback。",
    },
    "daily_report_messages": {
        "session_id": "关联日报生成会话 ID。",
        "sequence": "消息在会话内的严格递增序号。",
        "role": "消息角色：user 或 assistant。",
        "content": "消息正文。",
        "metadata": "助手消息的偏好建议等受控元数据。",
    },
    "daily_reports": {
        "session_id": "生成该最终日报的会话 ID。",
        "work_date": "日报对应的工作日期。",
        "content": "用户确认后的最终日报正文。",
        "source_input": "生成时的真实工作事实快照。",
        "prompt_version": "生成该日报采用的个人 Prompt 版本。",
        "model_name": "生成该日报草稿使用的模型名称。",
    },
    "user_relationships": {
        "actor_user_id": "发起关系的用户 ID。",
        "target_user_id": "被关注、忽略或屏蔽的目标用户 ID。",
        "relationship_type": "用户关系类型：follow、ignore 或 block。",
        "note": "关系备注；为空表示未填写。",
    },
    "private_message_participants": {
        "topic_id": "私信主题 ID。",
        "user_id": "参与私信的用户 ID。",
        "role": "私信参与者角色：owner 或 participant。",
        "last_read_post_number": "该参与者已读到的最高楼层编号。",
        "muted": "该参与者是否静音此私信主题。",
        "last_read_at": "该参与者最后阅读私信的时间；为空表示尚未阅读。",
        "joined_at": "加入私信时间。",
    },
}

COLUMN_COMMENTS.update(
    {
        "users": {
            **COLUMN_COMMENTS["users"],
            "display_name": "公开昵称；为空时使用 username。",
            "bio": "个人简介；按资料隐私设置公开。",
            "website_url": "个人链接 URL；按资料隐私设置公开。",
            "location": "个人所在地或时区文本；按资料隐私设置公开。",
            "profile_visibility": "资料可见性：public、members 或 private。",
            "show_activity": "是否在公开资料页展示活动流。",
            "interface_theme": "个人界面偏好：system、light 或 colorful。",
            "locale": "个人界面语言偏好。",
        },
        "calendar_events": {
            "title": "活动标题。",
            "description": "活动说明，支持 Markdown 原文。",
            "topic_id": "关联活动主题 ID；为空表示独立活动。",
            "created_by_id": "活动创建者 ID。",
            "start_at": "活动开始时间（UTC）。",
            "end_at": "活动结束时间（UTC）；为空表示未设置结束时间。",
            "timezone": "活动展示时区，如 Asia/Shanghai。",
            "location": "活动地点或线上会议链接。",
            "capacity": "活动最大报名人数；为空表示不限。",
            "rsvp_deadline": "报名截止时间；为空表示开始前均可报名。",
            "reminder_minutes_before": "活动开始前提醒分钟数；为空表示不提醒。",
            "status": "活动状态：scheduled 或 canceled。",
        },
        "event_rsvps": {
            "event_id": "活动 ID。",
            "user_id": "报名用户 ID。",
            "status": "报名状态：going 或 canceled。",
            "reminder_sent_at": "活动提醒发送时间；为空表示尚未发送。",
        },
        "chat_channels": {
            "slug": "聊天频道 URL 标识。",
            "name": "聊天频道名称。",
            "description": "聊天频道说明。",
            "channel_type": "频道类型：public、board 或 private。",
            "board_id": "关联版块 ID；全局或私密频道为空。",
            "created_by_id": "频道创建者 ID；系统创建时为空。",
            "message_count": "频道内未删除消息数量缓存。",
            "last_message_at": "最近一条消息发送时间；为空表示无消息。",
        },
        "chat_channel_members": {
            "channel_id": "聊天频道 ID。",
            "user_id": "频道成员用户 ID。",
            "role": "频道成员角色：owner、moderator 或 member。",
            "last_read_message_id": "该成员最后已读消息 ID；为空表示未读。",
            "last_read_at": "该成员最后阅读频道时间；为空表示尚未阅读。",
        },
        "chat_messages": {
            "channel_id": "聊天频道 ID。",
            "user_id": "发消息用户 ID。",
            "raw_text": "聊天消息原始文本。",
            "deleted_at": "消息软删除时间；为空表示未删除。",
        },
        "chat_presence": {
            "channel_id": "聊天频道 ID。",
            "user_id": "在线状态所属用户 ID。",
            "status": "在线状态：online、away 或 offline。",
            "last_seen_at": "用户在频道内最后活跃时间。",
            "typing_until": "输入中状态有效截止时间；为空表示未输入。",
        },
    }
)


def column_comment(table_name: str, column_name: str) -> str | None:
    return COLUMN_COMMENTS.get(table_name, {}).get(column_name) or COMMON_COLUMN_COMMENTS.get(
        column_name
    )


def iter_column_comments(table_name: str) -> Mapping[str, str]:
    comments: dict[str, str] = {}
    for column_name, comment in COMMON_COLUMN_COMMENTS.items():
        comments[column_name] = comment
    comments.update(COLUMN_COMMENTS.get(table_name, {}))
    return comments


def apply_schema_comments(metadata: MetaData) -> None:
    for table_name, table in metadata.tables.items():
        if table_name in TABLE_COMMENTS:
            table.comment = TABLE_COMMENTS[table_name]
        for column in table.columns:
            comment = column_comment(table_name, column.name)
            if comment:
                column.comment = comment
