from __future__ import annotations

from collections.abc import Mapping

from sqlalchemy import MetaData

COMMON_COLUMN_COMMENTS: dict[str, str] = {
    "id": "主键 UUID。",
    "created_at": "记录创建时间（UTC）。",
    "updated_at": "记录最后更新时间（UTC）。",
    "deleted_at": "软删除时间；为空表示未删除。",
    "user_id": "关联用户 ID。",
    "board_id": "关联版块 ID。",
    "topic_id": "关联主题 ID。",
    "post_id": "关联帖子 ID。",
    "target_type": "目标对象类型。",
    "target_id": "目标对象 ID。",
    "type": "业务类型。",
    "status": "当前状态。",
    "slug": "URL 友好的唯一标识。",
    "name": "显示名称。",
}

TABLE_COMMENTS: dict[str, str] = {
    "users": "用户账号、权限角色与账号状态。",
    "boards": "论坛版块/分类及版块统计计数。",
    "board_members": "版块成员、角色与通知订阅级别。",
    "board_invitations": "邀请制版块的成员邀请生命周期记录。",
    "tags": "主题标签及标签使用计数。",
    "topics": "论坛主题主表，保存主题状态、计数与排序信号。",
    "topic_tags": "主题与标签的多对多关联表。",
    "posts": "主题内帖子/楼层内容，保存原始 Markdown 与安全 HTML。",
    "post_revisions": "帖子编辑历史版本，保存编辑前正文、编辑人、原因和恢复来源。",
    "topic_reads": "用户对主题的阅读进度与主题通知级别。",
    "reactions": "用户对主题或帖子的点赞等表态记录。",
    "bookmarks": "用户收藏的主题或帖子。",
    "notifications": "通知中心消息及阅读状态。",
    "flags": "内容举报、处理状态与处理结果。",
    "reviewables": "统一审核对象，承载举报、待审内容、自动规则和申诉处理状态。",
    "reviewable_events": "审核对象事件流水，记录认领、释放、处理和申诉。",
    "audit_logs": "审核与管理操作审计日志。",
    "email_verification_codes": "邮箱注册验证码记录，用于账号激活和重发限流。",
    "uploads": "用户上传的头像、帖子图片和附件元数据及存储引用。",
    "user_security_tokens": "账号找回、邮箱变更等一次性安全令牌记录。",
    "user_sessions": "用户登录会话、刷新令牌哈希和设备撤销状态。",
    "user_recovery_codes": "TOTP 二次验证恢复码的哈希与使用状态。",
    "rate_limit_events": "写操作频控事件，用于用户/IP/邮箱等维度的滑动窗口计数。",
    "screened_rules": "邮箱、IP、URL 屏蔽名单规则及自动处置动作。",
    "spam_actions": "反垃圾系统自动拦截、禁言和频控处置记录。",
    "site_settings": "站点级可运营配置，包括品牌、注册开关和上传限制。",
    "background_jobs": "后台任务队列，保存待执行、重试、成功和死信任务。",
    "background_job_logs": "后台任务执行事件日志，用于排查失败、重试和死信。",
    "user_email_preferences": "用户邮件通知、摘要频率和投递禁用状态。",
    "email_delivery_events": "邮件供应商投递、退信和投诉事件记录。",
    "inbound_emails": "入站邮件回复 webhook 记录及匹配状态。",
    "backup_artifacts": "备份、导出归档元数据、校验和和状态记录。",
    "search_documents": "全文搜索索引文档，保存主题可搜索文本与过滤快照。",
    "search_logs": "搜索查询日志，用于无结果分析、热词统计和运营分析。",
}

COLUMN_COMMENTS: dict[str, dict[str, str]] = {
    "users": {
        "username": "登录名和公开显示用户名，唯一。",
        "email": "账号邮箱，唯一。",
        "hashed_password": "哈希后的登录密码。",
        "avatar_url": "用户头像 URL。",
        "role": "用户角色：普通用户、版主或管理员。",
        "level": "用户等级，默认 0，用于成长体系和权限展示。",
        "status": "账号状态：正常、禁言、封禁或删除。",
        "last_seen_at": "用户最后活跃时间。",
        "two_factor_enabled": "是否启用 TOTP 二次验证。",
        "two_factor_secret": "TOTP Base32 密钥；为空表示未完成启用。",
    },
    "email_verification_codes": {
        "user_id": "待验证用户 ID。",
        "email": "接收验证码的邮箱地址。",
        "code_hash": "验证码的不可逆哈希值。",
        "sent_at": "验证码邮件发送时间。",
        "expires_at": "验证码失效时间。",
        "consumed_at": "验证码成功使用时间；为空表示未使用。",
        "attempt_count": "该验证码已被尝试校验的次数。",
    },
    "boards": {
        "slug": "版块 URL 标识，唯一。",
        "name": "版块名称。",
        "description": "版块说明与讨论范围。",
        "color": "版块主题色。",
        "avatar_url": "版块头像 URL。",
        "owner_id": "版块拥有者用户 ID；为空表示系统拥有。",
        "visibility": "版块可见性：公开、私密或不列出。",
        "topic_count": "版块下未删除主题数量缓存。",
        "post_count": "版块下帖子数量缓存。",
        "follower_count": "关注/订阅该版块的用户数量缓存。",
    },
    "board_members": {
        "board_id": "所属版块 ID。",
        "user_id": "成员用户 ID。",
        "role": "成员在版块内的角色。",
        "notification_level": "该成员对版块的通知级别。",
        "joined_at": "加入或关注版块时间。",
    },
    "board_invitations": {
        "board_id": "被邀请加入的版块 ID。",
        "inviter_id": "发出邀请的用户 ID。",
        "invitee_id": "被邀请的用户 ID。",
        "status": "邀请状态：pending、accepted、declined、revoked 或 expired。",
        "expires_at": "邀请过期时间；为空表示当前首版不自动过期。",
        "responded_at": "邀请被接受、拒绝或撤回的时间。",
        "revoked_by_id": "撤回邀请的用户 ID；为空表示未撤回。",
    },
    "tags": {
        "name": "标签名称，唯一。",
        "slug": "标签 URL 标识，唯一。",
        "topic_count": "使用该标签的主题数量缓存。",
    },
    "topics": {
        "board_id": "主题所属版块 ID。",
        "user_id": "主题作者用户 ID。",
        "title": "主题标题。",
        "slug": "主题 URL 标识，在同一版块内唯一。",
        "status": "主题状态：开放、关闭、归档或隐藏。",
        "pinned": "是否置顶主题。",
        "featured": "是否标记为精选/高信号主题。",
        "view_count": "主题浏览次数缓存。",
        "reply_count": "主题回复数量缓存。",
        "like_count": "主题点赞数量缓存。",
        "hot_score": "主题热度分，用于热榜排序。",
        "last_posted_at": "最后发帖或回复时间。",
        "deleted_at": "主题软删除时间；为空表示未删除。",
        "merged_into_topic_id": "主题合并后的目标主题 ID；为空表示未合并。",
    },
    "topic_tags": {
        "topic_id": "主题 ID。",
        "tag_id": "标签 ID。",
    },
    "posts": {
        "topic_id": "帖子所属主题 ID。",
        "user_id": "发帖用户 ID。",
        "parent_id": "父帖子 ID，用于楼中楼/引用回复。",
        "post_number": "主题内楼层编号。",
        "raw_md": "用户提交的原始 Markdown 内容。",
        "cooked_html": "服务端渲染/清洗后的 HTML 内容。",
        "reply_count": "该帖子的直接回复数量缓存。",
        "like_count": "该帖子的点赞数量缓存。",
        "deleted_at": "帖子软删除时间；为空表示未删除。",
    },
    "post_revisions": {
        "post_id": "被编辑帖子 ID。",
        "topic_id": "被编辑帖子所属主题 ID，用于历史查询和审计关联。",
        "editor_id": "执行该次编辑或恢复操作的用户 ID；用户删除后为空。",
        "version_number": "同一帖子内递增的历史版本号，保存被覆盖前的内容版本。",
        "raw_md": "编辑前的原始 Markdown 内容。",
        "cooked_html": "编辑前已渲染/清洗的 HTML 内容。",
        "edit_reason": "编辑人填写的原因；为空表示未填写。",
        "summary": "系统生成或编辑人提供的版本摘要。",
        "restored_from_revision_id": "若该版本由恢复操作产生，指向被恢复的历史版本 ID；否则为空。",
        "created_at": "该历史版本保存时间（UTC）。",
    },
    "topic_reads": {
        "topic_id": "主题 ID。",
        "user_id": "用户 ID。",
        "last_read_post_number": "用户已读到的最高楼层编号。",
        "notification_level": "用户对该主题的通知级别。",
    },
    "reactions": {
        "target_type": "表态目标类型：主题或帖子。",
        "target_id": "表态目标 ID。",
        "user_id": "发起表态的用户 ID。",
        "type": "表态类型，目前为点赞。",
    },
    "bookmarks": {
        "target_type": "收藏目标类型：主题或帖子。",
        "target_id": "收藏目标 ID。",
        "user_id": "收藏用户 ID。",
    },
    "notifications": {
        "user_id": "接收通知的用户 ID。",
        "type": "通知类型。",
        "topic_id": "关联主题 ID。",
        "post_id": "关联帖子 ID。",
        "actor_id": "触发通知的用户 ID。",
        "data": "通知展示所需的结构化扩展数据。",
        "read_at": "通知被读取的时间；为空表示未读。",
    },
    "flags": {
        "target_type": "被举报目标类型：主题或帖子。",
        "target_id": "被举报目标 ID。",
        "board_id": "举报内容所属版块 ID。",
        "reporter_id": "举报人用户 ID。",
        "reason": "举报原因。",
        "detail": "举报补充说明。",
        "status": "举报处理状态。",
        "resolution_note": "处理结论说明。",
        "resolved_by_id": "处理该举报的管理员/版主用户 ID。",
        "resolved_at": "举报处理完成时间。",
    },
    "reviewables": {
        "type": "审核对象类型：flag、queued_topic、queued_post、queued_edit、appeal 或 system。",
        "status": (
            "审核状态：pending、claimed、approved、rejected、hidden、deleted、"
            "silenced、escalated 或 appealed。"
        ),
        "priority": "审核优先级，数值越小越靠前。",
        "source": "审核来源，如 flag、content_safety 或 spam_rule。",
        "source_summary": "可展示的来源摘要，不包含敏感规则明文。",
        "target_type": "审核目标类型；待发布内容可为空。",
        "target_id": "审核目标 ID；待发布内容可为空。",
        "board_id": "相关版块 ID；全局审核对象为空。",
        "topic_id": "相关主题 ID；新主题待审时为空。",
        "post_id": "相关帖子 ID；新内容待审时为空。",
        "flag_id": "关联举报 ID；非举报来源为空。",
        "created_by_id": "创建审核项的用户 ID；系统创建时为空。",
        "target_user_id": "被审核或受处理影响的用户 ID。",
        "assigned_to_id": "当前认领审核员 ID；未认领为空。",
        "assigned_at": "审核项被认领时间；未认领为空。",
        "resolved_by_id": "最终处理审核员 ID；未处理为空。",
        "resolved_at": "最终处理时间；未处理为空。",
        "data": "审核上下文 JSON，普通用户接口不得返回敏感字段。",
    },
    "reviewable_events": {
        "reviewable_id": "关联审核对象 ID。",
        "actor_id": "触发事件的用户 ID；系统事件为空。",
        "event": "事件类型：created、claimed、released、decided 或 appealed。",
        "from_status": "事件前审核状态；创建事件为空。",
        "to_status": "事件后审核状态。",
        "note": "审核员备注或申诉理由。",
        "data": "事件上下文 JSON，不包含密码或令牌。",
        "created_at": "事件发生时间（UTC）。",
    },
    "audit_logs": {
        "actor_id": "执行操作的管理员/版主用户 ID。",
        "action": "审计动作类型。",
        "target_type": "被操作目标类型。",
        "target_id": "被操作目标 ID。",
        "board_id": "相关版块 ID。",
        "data": "动作上下文和变更前后的结构化数据。",
        "created_at": "审计日志记录时间（UTC）。",
    },
    "uploads": {
        "user_id": "上传文件的用户 ID。",
        "board_id": "附件归属版块 ID；临时文件或头像为空。",
        "topic_id": "附件归属主题 ID；临时文件或头像为空。",
        "post_id": "附件归属帖子 ID；临时文件或头像为空。",
        "original_filename": "用户上传时的原始文件名，仅用于展示和下载名。",
        "storage_backend": "文件存储后端：local 或 s3。",
        "storage_key": "存储后端内的对象键，唯一且不含本地绝对路径。",
        "media_type": "服务端嗅探确认后的 MIME 类型。",
        "byte_size": "上传文件字节数。",
        "sha256": "文件内容 SHA-256 摘要，用于去重和审计。",
        "kind": "上传用途：post_attachment 或 avatar。",
        "status": "上传状态：temporary、attached、avatar 或 deleted。",
        "is_image": "是否为可内联展示的图片。",
        "expires_at": "临时上传过期时间；为空表示不自动过期。",
        "deleted_at": "上传软删除时间；为空表示仍可按权限读取。",
    },
    "user_security_tokens": {
        "user_id": "安全令牌所属用户 ID。",
        "purpose": "令牌用途：password_reset 或 email_change。",
        "token_hash": "一次性令牌的不可逆哈希值。",
        "email": "令牌发送目标邮箱；为空表示使用用户当前邮箱。",
        "payload": "令牌附带的 JSON 数据，如新邮箱地址。",
        "sent_at": "令牌发送时间。",
        "expires_at": "令牌失效时间。",
        "consumed_at": "令牌成功使用时间；为空表示未使用。",
        "attempt_count": "该令牌已被尝试校验的次数。",
    },
    "user_sessions": {
        "user_id": "会话所属用户 ID。",
        "refresh_token_hash": "刷新令牌的不可逆哈希值，用于撤销校验。",
        "user_agent": "登录设备/浏览器 User-Agent 摘要。",
        "ip_address": "登录请求来源 IP。",
        "last_seen_at": "该会话最后活跃时间。",
        "revoked_at": "会话撤销时间；为空表示仍有效。",
    },
    "user_recovery_codes": {
        "user_id": "恢复码所属用户 ID。",
        "code_hash": "恢复码的不可逆哈希值。",
        "used_at": "恢复码使用时间；为空表示仍可使用。",
    },
    "rate_limit_events": {
        "scope": "频控场景，如 register:ip 或 topic:user。",
        "identity_type": "频控主体类型：user、ip、email 或 account。",
        "identity_key": "频控主体归一化键。",
        "user_id": "触发频控事件的用户 ID；匿名路径为空。",
        "ip_address": "触发频控事件的请求来源 IP。",
        "created_at": "频控事件发生时间。",
    },
    "screened_rules": {
        "kind": "规则类型：email、ip 或 url。",
        "value": "管理员输入的原始屏蔽值。",
        "normalized_value": "用于匹配的归一化值。",
        "action": "命中后的处置动作：block 或 silence。",
        "note": "管理员备注；为空表示无备注。",
        "active": "规则是否启用。",
        "created_by_id": "创建规则的管理员 ID。",
    },
    "spam_actions": {
        "kind": "自动处置类型：rate_limit、screened_rule 或 new_user_screening。",
        "action": "自动处置动作：block 或 silence。",
        "reason": "触发处置的原因摘要。",
        "user_id": "被处置用户 ID；匿名注册/登录路径为空。",
        "ip_address": "触发处置的来源 IP。",
        "email": "命中的邮箱；非邮箱规则为空。",
        "url": "命中的 URL；非 URL 规则为空。",
        "screened_rule_id": "命中的屏蔽规则 ID；频控或新用户筛查为空。",
        "data": "处置上下文结构化数据，不包含密码或令牌。",
    },
    "site_settings": {
        "key": "设置键名，作为 API 与前端读取的稳定标识。",
        "value": "设置值，按 data_type 保存为 JSON 标量或对象。",
        "data_type": "设置值类型：string、boolean、integer 或 json。",
        "category": "设置分类，如 brand、access 或 uploads。",
        "description": "后台展示的设置说明。",
        "public": "是否可通过公开站点设置接口暴露给前端。",
        "updated_by_id": "最后修改该设置的管理员 ID；系统默认值为空。",
    },
    "background_jobs": {
        "queue": "任务队列名称，用于 worker 按队列拉取。",
        "task_name": "任务处理器名称。",
        "payload": "任务 JSON 载荷；不包含密码或大正文，邮件任务可含一次性发送密钥。",
        "status": "任务状态：queued、running、succeeded 或 dead。",
        "idempotency_key": "幂等键；非空时相同键只允许一个任务。",
        "priority": "任务优先级，数值越小越先执行。",
        "run_at": "任务最早可执行时间。",
        "attempts": "已尝试执行次数。",
        "max_attempts": "最大尝试次数，超过后进入 dead。",
        "locked_at": "任务被 worker 领取时间；为空表示未锁定。",
        "locked_by": "领取任务的 worker 标识。",
        "last_error": "最近一次失败错误摘要；成功时可为空。",
        "result": "任务成功结果摘要或失败上下文。",
        "finished_at": "任务最终完成或进入死信时间；未终结为空。",
    },
    "background_job_logs": {
        "job_id": "关联后台任务 ID。",
        "event": "任务事件类型，如 enqueued、started、succeeded、retry 或 dead。",
        "message": "事件说明。",
        "data": "事件结构化上下文，不包含密码、令牌或邮件密钥。",
        "created_at": "事件发生时间（UTC）。",
    },
    "user_email_preferences": {
        "user_id": "偏好所属用户 ID，唯一。",
        "email_enabled": "是否允许向该用户发送社区邮件。",
        "notify_replied": "被回复时是否发送邮件。",
        "notify_mentioned": "被提及时是否发送邮件。",
        "notify_liked": "帖子被点赞时是否发送邮件。",
        "notify_topic_new_post": "关注主题有新回复时是否发送邮件。",
        "notify_board_new_topic": "关注版块有新主题时是否发送邮件。",
        "digest_frequency": "摘要邮件频率：off、daily 或 weekly。",
        "last_digest_sent_at": "上次摘要邮件发送时间；为空表示从未发送。",
        "delivery_status": "邮件投递状态：ok、bounced、complained 或 disabled。",
        "disabled_reason": "邮件被自动或手动停发的原因；为空表示未停发。",
    },
    "email_delivery_events": {
        "user_id": "匹配到的用户 ID；未知邮箱为空。",
        "email": "投递事件涉及的邮箱地址。",
        "event_type": "事件类型：sent、delivered、bounce、complaint 或 dropped。",
        "kind": "邮件业务类型，如 notification_replied 或 email_digest。",
        "provider_message_id": "邮件供应商消息 ID；为空表示供应商未提供。",
        "reason": "退信、投诉或丢弃原因摘要。",
        "payload": "供应商原始事件的安全摘录，不包含认证密钥。",
        "created_at": "事件记录时间（UTC）。",
    },
    "inbound_emails": {
        "from_email": "入站邮件发件人邮箱。",
        "user_id": "匹配到的站内用户 ID；未知发件人为空。",
        "topic_id": "邮件声称回复的主题 ID；无法匹配时为空或记录原值。",
        "post_id": "邮件声称回复的父帖子 ID；可为空。",
        "provider_message_id": "入站邮件供应商消息 ID。",
        "raw_md": "入站邮件转换后的 Markdown/纯文本正文。",
        "status": "处理状态：accepted、unknown_sender、topic_not_found 或 recorded。",
        "reason": "未接受或仅记录的原因摘要。",
        "payload": "入站 webhook 原始上下文的安全摘录。",
        "created_at": "入站邮件记录时间（UTC）。",
    },
    "backup_artifacts": {
        "kind": "归档类型：site_backup、site_export 或 user_export。",
        "status": "归档状态：queued、running、succeeded、failed 或 deleted。",
        "filename": "下载文件名。",
        "storage_backend": "归档存储后端，当前为 local。",
        "storage_key": "归档在存储后端内的对象键；未生成或删除时为空。",
        "byte_size": "归档文件字节数。",
        "sha256": "归档文件 SHA-256 校验和。",
        "metadata": "归档元数据、表计数和安全摘录；不包含密码或令牌明文。",
        "failure_reason": "备份失败原因摘要；成功时为空。",
        "created_by_id": "触发备份或导出的管理员 ID；用户删除后为空。",
        "completed_at": "归档成功、失败或删除完成时间；队列中为空。",
    },
    "search_documents": {
        "topic_id": "关联主题 ID。",
        "board_id": "关联版块 ID。",
        "author_id": "主题作者用户 ID。",
        "author_username": "主题作者用户名快照。",
        "topic_status": "主题状态快照：open、closed 或 archived。",
        "title": "搜索索引中的主题标题。",
        "body": "可见帖子 Markdown 聚合正文。",
        "tags_text": "标签名称、标签 slug 和作者名聚合文本。",
        "indexed_at": "索引文档最后生成时间（UTC）。",
    },
    "search_logs": {
        "user_id": "搜索用户 ID；匿名搜索为空。",
        "query": "用户原始搜索词截断快照。",
        "normalized_query": "归一化搜索词，用于热词和无结果分析。",
        "filters": "搜索过滤条件 JSON 快照。",
        "result_count": "本次搜索返回结果数量。",
        "has_results": "本次搜索是否有结果。",
    },
}


def column_comment(table_name: str, column_name: str) -> str | None:
    return COLUMN_COMMENTS.get(table_name, {}).get(column_name) or COMMON_COLUMN_COMMENTS.get(
        column_name
    )


def iter_column_comments(table_name: str) -> Mapping[str, str]:
    comments: dict[str, str] = {}
    for column_name, comment in COMMON_COLUMN_COMMENTS.items():
        comments[column_name] = comment
    comments.update(COLUMN_COMMENTS.get(table_name, {}))
    return comments


def apply_schema_comments(metadata: MetaData) -> None:
    for table_name, table in metadata.tables.items():
        if table_name in TABLE_COMMENTS:
            table.comment = TABLE_COMMENTS[table_name]
        for column in table.columns:
            comment = column_comment(table_name, column.name)
            if comment:
                column.comment = comment
