export const queryKeys = {
  auth: ["auth"] as const,
  currentUser: ["auth", "me"] as const,
  sessions: ["auth", "sessions"] as const,
  oauthProviders: ["auth", "oauth", "providers"] as const,
  user: (username: string) => ["users", username] as const,
  userTopics: (username: string) => ["users", username, "topics"] as const,
  boards: ["boards"] as const,
  board: (slug: string) => ["boards", slug] as const,
  topics: (filter: string) => ["topics", filter] as const,
  topic: (id: string) => ["topics", "detail", id] as const,
  posts: (topicId: string) => ["topics", "posts", topicId] as const,
  postRevisions: (postId: string) => ["posts", postId, "revisions"] as const,
  postRevision: (postId: string, revisionId: string) =>
    ["posts", postId, "revisions", revisionId] as const,
  tags: (limit: number) => ["tags", limit] as const,
  invites: ["invites"] as const,
  notifications: ["notifications"] as const,
  emailPreferences: ["email", "preferences"] as const,
  siteSettingsPublic: ["site", "settings", "public"] as const,
  adminRoot: ["admin"] as const,
  adminSettings: ["admin", "settings"] as const,
  adminUsers: (params: object) => ["admin", "users", params] as const,
  adminSystem: ["admin", "system"] as const,
  adminAudit: ["admin", "audit"] as const,
  adminEmailLogs: ["admin", "email-logs"] as const,
  moderationRoot: ["moderation"] as const,
  moderationQueue: (status: string) => ["moderation", "queue", status] as const,
  moderationReviewables: (status: string) => ["moderation", "reviewables", status] as const,
  moderationMyReviewables: ["moderation", "reviewables", "me"] as const,
  moderationAudit: ["moderation", "audit"] as const,
};
