export const queryKeys = {
  auth: ["auth"] as const,
  currentUser: ["auth", "me"] as const,
  sessions: ["auth", "sessions"] as const,
  oauthProviders: ["auth", "oauth", "providers"] as const,
  user: (username: string) => ["users", username] as const,
  userTopics: (username: string) => ["users", username, "topics"] as const,
  userActivity: (username: string, type: string) => ["users", username, "activity", type] as const,
  userDirectoryRoot: ["users", "directory"] as const,
  userDirectory: (sort: string) => ["users", "directory", sort] as const,
  userRelationship: (username: string) => ["users", username, "relationship"] as const,
  privateMessages: ["users", "messages"] as const,
  events: (startAt = "", endAt = "") => ["events", startAt, endAt] as const,
  boards: ["boards"] as const,
  board: (slug: string) => ["boards", slug] as const,
  boardSettings: (slug: string) => ["boards", slug, "settings"] as const,
  topics: (filter: string) => ["topics", filter] as const,
  topic: (id: string) => ["topics", "detail", id] as const,
  topicAiSummary: (id: string) => ["topics", "detail", id, "ai-summary"] as const,
  posts: (topicId: string, sort?: string) =>
    sort ? (["topics", "posts", topicId, sort] as const) : (["topics", "posts", topicId] as const),
  postRevisions: (postId: string) => ["posts", postId, "revisions"] as const,
  postRevision: (postId: string, revisionId: string) =>
    ["posts", postId, "revisions", revisionId] as const,
  tagsRoot: ["tags"] as const,
  tags: (limit: number) => ["tags", limit] as const,
  invites: ["invites"] as const,
  notifications: ["notifications"] as const,
  pushSubscription: ["notifications", "push-subscription"] as const,
  emailPreferences: ["email", "preferences"] as const,
  siteSettingsPublic: ["site", "settings", "public"] as const,
  siteExtensions: ["site", "extensions"] as const,
  adminRoot: ["admin"] as const,
  adminSettings: ["admin", "settings"] as const,
  adminPlugins: ["admin", "plugins"] as const,
  adminAnalytics: (startDate: string, endDate: string) =>
    ["admin", "analytics", startDate, endDate] as const,
  adminAnalyticsReports: ["admin", "analytics", "reports"] as const,
  adminAnalyticsReport: (reportId: string, startDate: string, endDate: string) =>
    ["admin", "analytics", "reports", reportId, startDate, endDate] as const,
  adminBadges: ["admin", "badges"] as const,
  adminApiKeys: ["admin", "api-keys"] as const,
  adminExternalIntegrations: ["admin", "external-integrations"] as const,
  adminExternalIntegrationEvents: ["admin", "external-integrations", "events"] as const,
  adminMigrationExport: ["admin", "migrations", "export"] as const,
  githubIssuePreview: (url: string) => ["integrations", "github", "issue", url] as const,
  adminWebhooks: ["admin", "webhooks"] as const,
  adminWebhookDeliveries: ["admin", "webhook-deliveries"] as const,
  adminUsers: (params: object) => ["admin", "users", params] as const,
  adminSystem: ["admin", "system"] as const,
  adminAudit: ["admin", "audit"] as const,
  adminEmailLogs: ["admin", "email-logs"] as const,
  adminFrontierNewsRoot: ["admin", "frontier-news"] as const,
  adminFrontierNewsSources: ["admin", "frontier-news", "sources"] as const,
  adminFrontierNewsItems: (params: object) =>
    ["admin", "frontier-news", "items", params] as const,
  moderationRoot: ["moderation"] as const,
  moderationQueue: (status: string) => ["moderation", "queue", status] as const,
  moderationReviewables: (status: string) => ["moderation", "reviewables", status] as const,
  moderationPublishReviewables: (status: string) =>
    ["moderation", "reviewables", "publish", status] as const,
  moderationMyReviewables: ["moderation", "reviewables", "me"] as const,
  moderationAudit: ["moderation", "audit"] as const,
  drafts: ["drafts"] as const,
  draft: (targetType: string, targetId: string) => ["drafts", targetType, targetId] as const,
  topicNotificationLevel: (topicId: string) => ["topics", "notification-level", topicId] as const,
};
